# Generated by Django 3.2 on 2021-05-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_characters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characters',
            new_name='Character',
        ),
    ]
